on: push
name: Go
jobs:
  review:
    name: Review Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Lint Code
        uses: "cedrickring/golang-action@1.3.0"
        with:
          args: go get -u golang.org/x/lint/golint; go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status

      - name: Run Tests and Build
        uses: "cedrickring/golang-action@1.3.0"
